source/yocto/kirkstone.rst
source/yocto/mickledore.rst

We had some wrong indentations and
code-blocks were missing.
Signed-off-by: Norbert Wesp <n.wesp@phytec.de>

source: yocto: Some small fixes

---

source/yocto/kirkstone.rst
source/yocto/mickledore.rst

Linkcheck shows redirects and this commit takes over most of the redirects to the new target.

format: change website redirects

---

CONTRIBUTING.rst

Add a new FAQ file that (for now) highlights some common question that may arise.

BSPIMX8M-3058: Add faq section (focused for developers)

---

source/bsp/imx8/imx8mp/imx8mp.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst
source/conf.py

Create a i.MX8MP PD24.1.0 BSP Manual based on imx8mp mainline-head. 
@maintainers we need then a tag for this after this pull request has been merged.

BSPIMX8M-3167:  Create i.MX8MP PD24.1.0 documentation

---

source/yocto/mickledore.rst

Also updated phyLinux init walkthrough.

yocto: mickledore: Add new compatible BSP

---

source/bsp/imx8/imx8mm/bootmode-switch.rsti
source/bsp/imx8/imx8mn/bootmode-switch.rsti

Update HW revision notes for phyBOARD-Polis.

Polis boot switch hareware revision notes

---

source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst
source/conf.py

Update links to
1. PHYTEC Website
2. PHYTEC Download Server
3. device tree nodes
Update tags

BSPIMX8M-3258 Update links and tags to BSP mainline documentation

---

source/bsp/imx-common/development/uuu.rsti

SPI NOR Flash can also be flashed via UUU-Tool. Add a chapter on how to do that.

bsp: imx-common: development: uuu: add how to flash SPI NOR Flash

---

source/locale/zh_CN/LC_MESSAGES/bsp.po
source/locale/zh_CN/LC_MESSAGES/contributing_links.po
source/locale/zh_CN/LC_MESSAGES/yocto.po

initial chinese translation for bsp, yocto and contributing links

initial chinese translation

---

README.rst

Add build tools required for chinese language support.

README: Add system tool requirements for chinese language

---

source/conf.py

This reverts commit 8990940cf3bd6f64bfe30a60bc77250960ea3a88.
Reference #231.

Revert "zh_CN: hide translation until final review"

---

source/rauc/scarthgap.rst

Describe RAUC's adaptive updates and that we have this enabled by default in our bundles.

source: rauc: Describe adaptive updates

---

source/conf.py

Update copyright information from 2024 to 2025.

conf: update copyright to 2025

---

source/locale/zh_CN/LC_MESSAGES/bsp.po
source/locale/zh_CN/LC_MESSAGES/rauc.po

rauc: first chinese translation
bsp: update chinese translation

bsp: update chinese translation

---

source/bsp/imx8/imx8mm/head.rst
source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mm/pd25.1.0.rst
source/bsp/imx8/imx8mn/head.rst
source/bsp/imx8/imx8mn/pd22.1.1.rst
source/bsp/imx8/imx8mn/pd23.1.0.rst
source/bsp/imx8/imx8mp-libra-fpsc/head.rst
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd22.1.2.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst
source/bsp/imx8/imx8mp/pd24.1.0_nxp.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst
source/bsp/imx8/imx8mp/pd24.1.2.rst

Who is this mirco and what has he to do with USB ports?

bsp: imx8: Fix typo concerning USB port

---

source/bsp/imx9/imx95/alpha1.rst

Only describe the EEPROMs and the usage.

imx95: alpha1: add eeprom section

---

source/bsp/imx8/imx8mp-libra-fpsc/display.rsti
source/bsp/imx8/imx8mp-libra-fpsc/head.rst

Currently only LVDS0 (onboard lvds) is supported.

BSPIMX8M-3644 imx8mp-libra: update display chapter

---

source/bsp/imx-common/peripherals/eeprom.rsti
source/bsp/imx8/imx8mp-libra-fpsc/head.rst
source/bsp/imx9/imx95/alpha1.rst
source/bsp/imx9/imx95/head.rst

Add description for imx8mp-libra EEPROMs. Very similar to imx95.

BSPIMX8M-3629 Wip/bhahn/bspimx8 m 3629 imx8mp libra eeprom

---

source/conf.py
source/sphinx/static/googledd12f2e41658d61e.html

This reverts commit 27f832fc7646c26d920a88814484516f6f27b47b introduced in #237.
Cleanup, as I will not be able to monitor the traffic in the future. Other maintainer could register a new hash with their account in the future.

Revert "SEO: add html file for google-site-verification"

---

source/bsp/imx8/imx8mp-fpsc/quickstart-alpha1.rst
source/bsp/imx9/imx95-fpsc/quickstart-alpha1.rst

imx95-fpsc: quickstart-alpha1: use generic display
Add article which should be used for all FPSC kits.
imx8mp-fpsc: quickstart-alpha1: update
release date
hw manual

update fpsc: quickstart-alpha1
