phytec/doc-bsp-yocto

.github/workflows/build.yaml
.github/workflows/compliance.yaml
.github/workflows/deploy.yaml
.github/workflows/linkcheck.yaml
.github/workflows/release.yml
.github/workflows/spelling.yaml

Since the repository is now public, we can activate github runners instead of self-hosted runners.

gh actions: move to github runner

---

tox.ini

We can let sphinx create only the latex files, but not compile them. Once the latex files exist, we can build them in parallel with make.
#147 
resolves #147

tox: silence latex and build in parallel

---

source/sphinx/static/css/phytec-theme.css

The darker color is already used by the documentation of modules developed in US. In addition it looks more elegant. This commit adapts the color scheme (logo background and chapter-headings).
The Chapter-Headings in HTML are not very ergonomic in terms of contrast, but there is no useful information in them anyway (Contents, Contribute) and the immediate focus falls on the headings (Yocto Reference Manuals, i.MX 8 Manuals).
Reference US Modules:
https://docs.phytec.com/latest/phycore-am62x/developingwithyocto/index.html
Old:
US Docs color:
New "teal4"

static: change teal color to darker Phytec color

---

source/contributing_links.rst

The repository is now public and the contributing section was lacking some information and pointers to the right places.

contribute: rephrase contributing section

---

source/bsp/getting-started.rsti
source/bsp/imx8/imx8mp/imx8mp.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/intro.rsti
source/conf.py

For upcoming imx8mp mainline BSP release, add a manual.
This is done because the content and structure may be different from vendor releases. Since the plan is to move back to vendor release after the mainline release, we do not work on the head manual and branch off early.
Add some misc. improvements that I noticed during proofreading.
Depends on #145

BSPIMX8M-3139: create PD24.1.0.rst BSP manual

---

source/bsp/imx8/imx8mm/head.rst
source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst

Links for mcore-zephyr-docs substitution were broken, because the link got changed.

bsp: imx8: update links for mcore-zephyr-docs

---

source/bsp/imx8/imx8mp/mainline-head.rst

For the mainline BSP, only on-board LVDS is working. There are no overlays upstream and HDMI is not supported, yet. Include only a very basic section about display support.

bsp: imx8mp: mainline-head: update display section

---

source/bsp/imx9/imx93/pd24.1.0.rst

The link is currently not used in the imx93 documentation, but it causes the linkcheck to fail.

linkcheck: fix broken link to Zephyr documentation

---

.github/workflows/release.yml

The release action builds and uploads all pdf that have been generated. This commit corrects the path to the build directory for the pdf files.
Linkcheck should pass after rebase once #160 got merged.

gh actions: release: fix latex path

---

source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/peripherals/video.rsti

Rework peripherals video chapter.
use gst-play-1.0 instead of gplay-1.0, because gplay-1.0 is only in nxp-bsp. And gst-play is the same as gplay, but is also present upstream.
Change the gst-launch example with filesrc, because this was only working for h264 videos and the sync=false option causes the video to play too fast. Replace it with an option that works for all videos and will play the video at normal speed.
Remove kmssink chapter, because kmssink is not working.
Dissolve the chapter into the mainline-bsp manual and add mainline-bsp specific parameter.
Add note, that mainline BSP only supports software rendering at the moment.

Rework peripherals video chapter

---

source/bsp/imx8/peripherals/eeprom.rsti

Fix a documentation issue reported by the customer the when filling the EEPROM with zeros. The EEPROM data should not be overwritten. Also extend and move the EEPROM data warning to the start of the "I2C EEPROM on |som|" chapter.
@cstoidner I see that you have your own imx9 eeprom chapter. But you have basically the same issue. Should I fix it, too?

BSPIMX8M-3177: Wip/tremmet/i2c eeprom erase

---

source/conf.py
source/yocto/manual-index.rst
source/yocto/scarthgap.rst

Official links to new scarthgap yocto ref-manual are
set to dev-state instead of scarthgap, as the ref-manual
is not available for scarthgap right now.
Signed-off-by: Norbert Wesp <n.wesp@phytec.de>

yocto: scarthgap: Add new documentation

---

CONTRIBUTING.rst
source/bsp/imx-common/development/standalone_build.rsti
source/bsp/imx8/development/standalone_build.rsti
source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mn/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/yocto/kirkstone.rst
source/yocto/mickledore.rst

This is a follow-up to #84. It adds the hint for building Devicetrees only which I found quite useful in the past. Additionally, it highlights the optional character of creating a branch (as it was already for uboot standalone) and switches the 'git checkout -b' calls to 'switch --create' as this IMHO better describes what is done there (and is more telly). Finally, I added changed directories to  the prompts for better overview in longer command lists.

Update the standalone build sections

---

source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/peripherals/pm.rsti

remove chapters about unsupported features:
- no SPI NOR Flash support
- no suspend to RAM support
- no support for EEPROM ID-Page
- no support for audio

Wip/bhahn/BSPIMX8M-3179: cleanup mainline head for release

---

source/bsp/getting-started.rsti
source/bsp/imx-common/development/format_sd-card.rsti
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mn/pd23.1.0.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst

Flashing a partup images created with Yocto versions mickledore or newer do not work when the systems resize2fs version is, too old (1.46.6 and older).
The newest E2fsprog versions has a new default option enabled in the filesystem, which is not compatible with older versions. 
https://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.47.0
As we support Ubuntu 22.04 as host system we do see the issue there.
Make flashing an SD-Card from host with bmap as first option in the documentation and add a note in the partup section.
As the same issue appears when using gparted and a note there, too.

BSPIMX8M-3204: Descibe partup issue due to new default option in resize2fs

---

source/bsp/imx8/imx8mm/head.rst
source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mn/head.rst
source/bsp/imx8/imx8mn/pd22.1.1.rst
source/bsp/imx8/imx8mn/pd23.1.0.rst
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst
source/bsp/imx8/peripherals/eeprom.rsti

Based on BSPIMX8M-3205 =>probably needs rebase when that is merged. => only the last commit is new
Update description at the beginning. There are not two EEPROMs it is one
with two different addresses.
Starting with PD24.1.0 the EEPROM ID-page will not be accessible via the
sysfs anymore. Change that in the description. Update command for
restoring 0x51 EEPROM to U-Boot.
Remove the "Rescue EEPROM Data" chapter for new manuals and dissolve it
for PD22.1.1 and PD23.1.0. The command does not work for newer versions.
For newer versions move the note to contact our support to the top.

Wip/bhahn/BSPIMX8M-3208: bsp: imx8: rework EEPROM chapter

---

README.rst

The documentation badge was broken and is not really needed as the status of the latest deploy build is always shown in the top row that also shows the latest commit.

readme: remove documentation badge

---

source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mn/pd22.1.1.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst

We got a customer request that the RAUC docu link needs to be updated to the latest version for the i.MX8MP Mainline Release.
Also add a link to the RAUC documentation for the PD22.1.1 release.

Wip/tremmet/imx8mp pd24.1.0 RAUC doc version 

---

source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst

Add back backlight control chapter and add a note that on brightness level 1 there is visible backlight flickering probably due to timing problems with the hardware.

BSPIMX8M-3270 bsp: imx8mp: mainline-head: Add back backlight control chapter

---

source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst

The imx8mp platform uses the variant MIMX8ML8 that includes a cortex M7 processor. This commit fixes the core that has been identical with the imx8mm (M4) previously.

imx8: fix coprocessor target

---

source/bsp/imx8/imx8mp/mainline-head.rst

- Add notes about flashing limitations in U-Boot
- Update examples using headless image
- Update USB flash headline
This pull request is based on https://github.com/phytec/doc-bsp-yocto/pull/186
So it needs a rebase on main after Yannic's pull request got merged.

BSPIMX8M-3264: Add notes about flashing limitation in U-boot

---

source/bsp/imx8/imx8mp/imx8mp.rst
source/bsp/imx8/imx8mp/pd24.1.2.rst
source/conf.py

Created PD24.1.2 minor mainline release documentation with the release information and compatile BSP information.
Added pd24.1.2.rst to the imx8mp.rst index file and to the pdf output conf.py file.

imx8: imx8mp: create pd24.1.2 mainline documentation

---

source/bsp/imx8/imx8mm/head.rst

Polis-4 machine will no longer be supported. Remove the sdcard reset limitation from the imx8mm head manual.

BSPIMX8M-3311 bsp: imx8mm: remove traces of polis-4 machine

---

.github/workflows/build.yaml
.github/workflows/cleanup_doc_preview.yaml
CONTRIBUTING.rst

GitHub pages can host documentation previews for each pull request. This can be helpful for reviewing and getting an overview of changes quickly.
For testing check the passed checks:
`Check External Links / Click on details for a Doc Preview (pull_request)`

GH actions: add status check with documentation preview

---

source/bsp/imx9/mcu.rsti

The missing space before the '>' is quite confusing, especially as the choosable firmware name is also marked with "<...>".

imx9: mcu: Add missing space in firmware load command for remoteproc

---

source/bsp/imx-common/development/standalone_build_preface.rsti

To build the standalone kernel successfully by overcoming the openssl error, need to install the libssl-dev package. update made to the ubuntu dependencies for standalone kernel build in the standalone build
preface.

BSPIMX8M-3281: bsp: imx-common: standalone_build_kernel: Add note to the kernel build

---

source/bsp/imx8/imx8mp/pd24.1.2.rst

Fix the the compatible BSPs table and use the full BSP name via "yocto-manifestname".

imx8mp-pd24.1.2: Fix compatible BSPs table

---

source/bsp/imx8/imx8mm/imx8mm.rst
source/bsp/imx8/imx8mn/imx8mn.rst
source/bsp/imx8/imx8mp/imx8mp.rst
source/bsp/imx9/imx93/imx93.rst

Mainline BSPs and vendor BSPs can have the same PD name as hinted in https://github.com/phytec/doc-bsp-yocto/pull/201#discussion_r1672213651. It is important to differentiate in the name of the BSP documents.
The Phytec Download section differentiates between Mainline and Vendor BSPs clearly. However, if customers browse the documentation it it not clear from the document overview what kind of BSP is described.
**Do not merge yet:**

doc: use full bsp name for html documents

---

source/bsp/imx8/imx8mp/imx8mp.rst
source/bsp/imx8/imx8mp/pd22.1.2.rst
source/conf.py

Create PD22.1.2 BSP manual based on the PD22.1.1 BSP manual. 
- Adjust all the external links.
- Adjust Kernel and U-Boot tag
- Adjust internal references
- Adjust BSP version and release date
Wait for merge until PD22.1.2 is released for all the external links to work.

BSPIMX8M-3377 i.MX8MP-PD22.1.2 BSP manual

---

.github/workflows/deploy.yaml

As of now only the release action has been build, but the site did not got deployed to github pages. This change makes the deploy action run after the release has been created.

gh actions: Deploy on release

---

source/bsp/imx-common/development/standalone_build_kernel.rsti

Make sure that the nproc command is actually called and not that a variable is passed. As if ${nproc} is empty it leads to unlimited number of jobs being created and can make the system unresponsive.

imx-common: standalone_build_kernel: Fix make parameter

---

source/bsp/imx8/development/kernel-standalone.rsti
source/bsp/imx8/development/uboot-standalone.rsti
source/bsp/imx8/imx8mp/head.rst

We switch bootscript to FIT image as well as kernel+dt. Document changes needed when compiling kernel.
---
I rearranged the standalone build section. I often find myself looking for them as reference, but they are not displayed in the toctree.
Further, I think it is more logical to put them first, i.e. before host setup. It is not required and when you want to compile kernel and copy to SD card, there is no need to go through these sections first.

BSPIMX8M-3356 document FIT image standalone build

---

source/bsp/imx8/imx8mp/display.rsti
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst

HDMI weston mode which should be used in weston.ini changed from "current" to "preferred".

bsp: imx8mp: display: Adjust HDMI weston mode

---

source/bsp/imx-common/peripherals/display.rsti
source/bsp/imx8/dt-overlays.rsti
source/bsp/imx8/imx8mm/head.rst
source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mn/head.rst
source/bsp/imx8/imx8mn/pd22.1.1.rst
source/bsp/imx8/imx8mn/pd23.1.0.rst
source/bsp/imx8/imx8mp/display.rsti
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd22.1.2.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst
source/bsp/imx8/imx8mp/wireless-network.rsti
source/bsp/imx8/mcu.rsti
source/bsp/peripherals/wireless-network.rsti

- remove old outdated hci info
- peb-av-10 overlay got renamed for new imx8mp PD24.1.0 NXP BSP
- add note that some boards might have multiple backlight controls

Wip/bhahn/BSPIMX8M-3386 BSPIMX8M-3342

---

source/bsp/imx8/imx8mp/head.rst

To fit the PHYTEC repo naming scheme we updated the recipe name to linux-phytec-imx_*.bb. Update documentation, too.

bsp: imx8mp: head: Update linux recipe name

---

source/bsp/imx-common/development/standalone_build_kernel.rsti

The code block wasn't correctly formatted. Fixes 9badff3380f40

bsp: imx-common: standalone_build_kernel: Fix indentation

---

.github/workflows/build.yaml
.github/workflows/deploy.yaml
.github/workflows/release.yml
.gitignore
CONTRIBUTING.rst
README.rst
requirements/build.txt
scripts/check_filesize.sh
source/conf.py
source/locale/zh_CN/LC_MESSAGES/bsp.po
source/locale/zh_CN/LC_MESSAGES/contributing_links.po
source/locale/zh_CN/LC_MESSAGES/index.po
source/locale/zh_CN/LC_MESSAGES/sphinx.po
source/locale/zh_CN/LC_MESSAGES/yocto.po
source/sphinx/templates/versions.html
tox.ini

This PR is a draft on how to add internationalization to the project. Pushing to test the GitHub actions compatibility and review. ~More information coming soon.~
Spinx can automatically generate text files (*.pot, *.po) that contain translation references, called messages (more [details](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html)). Those messages are broken down in paragraphs. For simplified Chinese (zh_CN) the files are located at:
```
doc-bsp-yocto/source/locale/zh_CN/
└── LC_MESSAGES
├── bsp.po
├── contributing_links.po
├── index.po
├── sphinx.po
└── yocto.po
```
The file bsp.po contains a list of messages (strings to be translated) found in all BSP manuals. This looks as follows:
```
#: ../../source/bsp/getting-started.rsti:27 …
```

Sphinx: add internationalization

---

CONTRIBUTING.rst
tox.ini

We agreed to not wrap lines in the translation messages. This is an option that can be set in Poedit. This commit represents the related setting in Sphinx.
Follow-up PR to #229

translation: do not wrap lines

---

source/bsp/imx8/installing-os.rsti

When loading a complete image into RAM, use the space after OP-TEE, i.e. 0x58000000. Even for the smallest RAM size (1GB) we have 671 MB after OP-TEE and 369MB before OP-TEE.

BSPIMX8M-3498 bsp: imx8: installing-os fix load addr for image

---

source/bsp/dt-overlays.rsti
source/bsp/imx8/imx8mp/head.rst

Handling of device tree overlays changed due to introduction of loading and executing an external boot script.
As the boot script can be used for all PHYTEC products (using U-Boot) make a generic include file for overlay handling.
The new file is mostly a copy of the existing imx8 one, but does not contain any product specific info (examples include a specific expansion board, though).
This PR introduces a generic dt-overlays file, that may be included by any product family.
In addition the imx8mp includes this newly generated file as it is the only product making use of the U-Boot standard boot bootflow.

BSPIMX8M-3496 adapt dt-overlays chapter to external boot script

---

source/bsp/imx8/imx8mm/head.rst
source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mn/head.rst
source/bsp/imx8/imx8mn/pd22.1.1.rst
source/bsp/imx8/imx8mn/pd23.1.0.rst
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd22.1.2.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst
source/bsp/imx8/imx8mp/wireless-network.rsti
source/bsp/peripherals/wireless-network.rsti

Small updates for Bluetooth and wifi contain:
- Update overlays parameter names for fitImage configs on i.MX8MP
- Add a note in the Bluetooth chapter where PEB-WLBT-05 configuration can be found (i.MX8MP)
- Make UART device for Bluetooth configurable. It was set fix to UART3 but this only fits for i.MX8MP and not i.MX8MM/N 
- wpa-suplicant command output changed
- wifi is automatically configured as DHCP in scarthgap. No need to explain how to set this up

BSPIMX8M-3419: Bluetooth and Wifi updates

---

requirements/build.txt
source/conf.py
source/sphinx/static/robots.txt

the sphinx extension `sphinx-sitemap` allows to generate a sitemap automatically. robot.txt points to the sitemap so that the documentation page is better indexed and users can find it easier when they search for a topic in their search engine.

SEO: add sitemap, robot.txt

---

source/bsp/imx8/imx8mm/head.rst
source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mn/head.rst
source/bsp/imx8/imx8mn/pd22.1.1.rst
source/bsp/imx8/imx8mn/pd23.1.0.rst
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst
source/bsp/imx8/imx8mp/pd24.1.2.rst
source/bsp/imx9/imx93/pd24.1.0.rst
source/bsp/imx9/imx93/pd24.1.1.rst
source/conf.py
source/yocto/kirkstone.rst
source/yocto/mickledore.rst
source/yocto/scarthgap.rst
tox.ini

This PR adds the option to download a manual as a pdf file.
Currently there are two issues with the pdf files:
1. The release in the pdf files is the documentation release (e.g. `imx8mp-pd24.1.2-2-gb7c1ba7`). This is confusing for customers that e.g. view an imx93 manual with that release string. Renaming the release string from `Release` to `Documentation Build` may reduce confusions.
2. When providing pdf documents for head versions, we should probably mark them clearly to indicate that those are not final releases.
**Edit:**
To 1.: The release version is no longer shown on the title page, but on the left side of the header as `Documentation rev.`:.
To 2: The right side of the header now shows the release number or `DRAFT` for head manuals.
**Note:** As this PR is based on #203, you can …

PDF: add download links to all manuals

---

source/conf.py
source/sphinx/static/googledd12f2e41658d61e.html

Depends on #236 to be merged
Adding this file allows to check https://github.com/phytec/doc-bsp-yocto/ in the Google Search Console. This will not track any users or collect any data, it only allows to analyze the website to check if the newly introduced sitemap works properly.

SEO: add html file for google-site-verification

---

.github/workflows/deploy.yaml

The pdf documentation has been build in the build action, but not in the depoy action. Since pdf files are now linked in the manuals, the pdf build action has to be triggered in the deploy action as well.
Just noticed after merging #204 that I forgot to execute the pdf build in the deploy action.

gh action: deploy: add building of pdf documentation

---

.github/workflows/deploy.yaml

The deploy action builds the pdf since #238 is merged. The deploy action now takes longer than 5 min to build everything.

gh action: deploy: increase timeout

---

source/bsp/peripherals/emmc.rsti

Move resize fs note to end of the chapter to make clearer that the previous commands build up on top of each other.
Second attempt of the chapter update.

BSPIMX8M-3415: source: bsp: emmc: Move resize fs note

---

source/bsp/imx8/installing-os.rsti

Set the default or initial flashing of eMMC via kernel. The U-Boot way of eMMC flashing is slow and image size is limited by RAM space. So, updated with flashing eMMC via kernel sections first before U-Boot.
Also Updated for SPI NOR Flash sections.

BSPIMX8M-2641: bsp: imx8: installing-os: Update default eMMC flashing

---

source/bsp/imx8/efi.rsti
source/bsp/imx8/imx8mp/head.rst
source/bsp/installing-distro-efi.rsti

For the new PD24.1.0 release booting with efi is supported. Add a chapter on how to turn on/off booting with efi and how to install a distro and boot it with efi.

BSPIMX8M-3424 bsp: imx8mp: Add chapter about booting efi

---

.github/workflows/deploy.yaml

Currently each deploy action and subsequent push to the gh-pages branch adds a commit with build artifacts. This makes the size of the branch very large over time.
To fix this issue the action-gh-pages supports the orphan option, which creates a new commit without considering the build history, effectively overwriting the whole branch at each deploy.

gh actions: do not preserve history on gh-pages branch

---

source/bsp/imx9/imx93/imx93.rst
source/bsp/imx9/imx93/pd24.1.0.rst
source/bsp/imx9/imx93/pd24.1.1.rst
source/bsp/imx9/imx93/pd24.2.0.rst
source/bsp/imx9/imx93/peripherals/pm.rsti
source/bsp/imx9/imx93/wireless-network.rsti
source/bsp/imx9/installing-os.rsti
source/bsp/imx9/peripherals/tm.rsti
source/bsp/peripherals/wireless-network.rsti
source/conf.py

Add i.MX93 documentation update for the PD24.2.0 release.
Changes:
- Component versions update (based on NXP lf-6.6.23-2.0.0)
- Rename PEB-AV-10 overlay
- Add additional overlays
- Bootloader unified defconfig
- Kernel defconfig changes
- Note about disabled VFS driver on 900MHz CPU
- Rename output images to contain ".rootfs."

i.MX93 PD24.2.0 update

---

source/bsp/imx9/imx93/pd24.2.0.rst
source/conf.py

As described in #228, this is a follow-up PR to enable and link the pdf version of the manual.

bsp: imx93: add pdf build, link to html documentation

---

source/conf.py

When adding a language prefix, this would also affect the english version, which currently does not have a language code as it is the default. Therefore remove alternative links and only add the basic links without language code to the sitemap.
Fix to #236  after checking google search console.

seo: fix sitemap, remove alternate links

---

.github/workflows/release.yml

As general support for pdf manuals in chinese language has been added, an invocation of the pdf build will build pdf files in all languages. This commit adds tex support for chinese language to the build machine as the release action will otherwise fail.
Note: PDF files are build for all languages, but only filed for the default language (en).

gh actions: fix release action

---

source/bsp/imx8/imx8mp/head.rst

Update all links, as well as the U-Boot and Kernel tags for the new NXP PD24.1.0 release.

BSPIMX8M-3299 bsp: imx8mp: update head for PD24.1.0 NXP release

---

source/bsp/imx8/development/legacy_boot_deprecated.rsti
source/bsp/imx8/imx8mp/head.rst

For imx8mp NXP PD24.1.0 we switched to standardboot and booting the kernel from a fitimage. We decided to keep the possibility to easily switch back to the old method of booting (legacyboot). This option is marked as depricated and will be removed in the future. Add a chapter on how to switch back to legacyboot.

BSPIMX8M-3483 bsp: imx8: add how to switch back to legacyboot

---

source/yocto/scarthgap.rst

We have more supported releases on scarthgap.
The output of "phyLinux init" has to be updated as well.
Also adjust the releasedate of BSP-Yocto-NXP-i.MX8MP-PD24.1.0.

yocto: scarthgap: add new releases and update init part

---

source/bsp/imx8/imx8mp/pd24.1.0_nxp.rst

Links in the pd24.1.0_nxp documentation should not point to head manual. Make them point to the pd24.1.0_nxp manual.
solves https://github.com/phytec/doc-bsp-yocto/issues/250

bsp: imx8mp: pd24.1.0_nxp: update links in documentation

---

source/bsp/dt-overlays.rsti
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/pd24.1.0_nxp.rst

Update the remoteproc substition variable "dtbo-rpmsg" with the prefix "conf-" for head.rst and pd24.1.0_nxp.rst.

bsp: imx8mp: Fix remoteproc overlay substitution variable

---

source/yocto/kirkstone.rst
source/yocto/mickledore.rst
source/yocto/scarthgap.rst

Did not fix the id in the translation file, nor the translated string.
Fixes #253

source: yocto: Fix headline for own-layer-creation section

---

source/bsp/imx8/peripherals/eeprom.rsti
source/bsp/imx9/peripherals/eeprom.rsti
source/locale/zh_CN/LC_MESSAGES/bsp.po

Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>

eeprom: fix 256 bytes typo

---

CONTRIBUTING.rst
source/bsp/building-bsp.rsti
source/bsp/imx-common/development/standalone_build_u-boot_imxmkimage.rsti
source/bsp/imx-common/development/uuu.rsti
source/bsp/imx8/imx8mm/head.rst
source/bsp/imx8/imx8mm/pd22.1.1.rst
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mn/head.rst
source/bsp/imx8/imx8mn/pd22.1.1.rst
source/bsp/imx8/imx8mn/pd23.1.0.rst
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd22.1.1.rst
source/bsp/imx8/imx8mp/pd22.1.2.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst
source/bsp/imx8/imx8mp/pd24.1.0_nxp.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst
source/bsp/imx8/imx8mp/pd24.1.2.rst
source/bsp/imx8/peripherals/gpios.rsti
source/bsp/imx9/imx93/pd24.1.0.rst
source/bsp/imx9/imx93/pd24.1.1.rst
source/bsp/imx9/imx93/pd24.2.0.rst
source/bsp/peripherals/pcie.rsti
source/bsp/peripherals/wireless-network.rsti
source/yocto/kirkstone.rst
source/yocto/mickledore.rst
source/yocto/scarthgap.rst

This PR fixes some issues that have been found while reviewing the translation system.
- Move external ilnks to doc-bsp-yocto to sphinx references
- Reduce some unneded substitutions
- minor fixes that I saw on the way

fixes: fix issues found during translation review

---

scripts/clean_po_files.sh
source/locale/zh_CN/LC_MESSAGES/bsp.po
source/locale/zh_CN/LC_MESSAGES/contributing_links.po
source/locale/zh_CN/LC_MESSAGES/index.po
source/locale/zh_CN/LC_MESSAGES/rauc.po
source/locale/zh_CN/LC_MESSAGES/sphinx.po
source/locale/zh_CN/LC_MESSAGES/yocto.po
tox.ini

~Based on #263~
@annie-pixel I removed the comment lines in the po files, as those cause very large diffs at minimal changes of the content. Can you check if you observe any disadvantages when using the po files with poedit.

Update po files, containing translation messages

---

source/yocto/kirkstone.rst
source/yocto/mickledore.rst
source/yocto/scarthgap.rst

Did not fix the id in the translation file, nor the translated string.

yocto: Fix headline duplication

---

source/bsp/peripherals/introduction.rsti

bsp: periphals: introduction: Fix spelling "reused"

---

source/conf.py
source/coprocessor/coprocessor.rst
source/coprocessor/index.rst
source/index.rst

This PR adds an application manual that describes the openAMP framework and how to work with coprocessors. 
The "Examples and Resources" section describes in more detail how to get the openamp_rsc Zephyr example to work with the phyBOARD Pollux.
For now this is just an idea to collect relevant information about the development with integrated coprocessors. This PR is not yet in a state that can be merged, there are many open points (marked with TODO).
The goal for this manual would be to give some guidelines on how to efficiently use coprocessors that are integrated in most SoCs. Among others, it may cover the following points and provide architectural guidance and links to code examples.
- Benchmarking
- Data exchanges with a common protocol manifests (Zephyr, Linux) with e.g. Protocol …

Add initial version of a Coprocessor Application Manual

---

source/locale/zh_CN/LC_MESSAGES/bsp.po
source/locale/zh_CN/LC_MESSAGES/coprocessor.po
source/locale/zh_CN/LC_MESSAGES/rauc.po
source/locale/zh_CN/LC_MESSAGES/yocto.po

Update the translation messages in the `.po` files to be in sync with the content.
Note:
This is a regular update of the translation messages. The content change slightly over time and smaller issues get fixed permanently. That means that we have to update the translation messages from time to time to be in sync.
This PR also fixes an issue that is currently causing the spellcheck action runner to fail (misspelled word "re-used").
@annie-pixel can you check with this PR if this makes it easy for you to update the translated strings in a follow-up PR? If you think that is the case, we can merge this and you can work on the translation update after that.

intl: update internationalization

---

source/bsp/peripherals/rs485-fullduplex.rsti
source/bsp/peripherals/rs485-halfduplex.rsti
source/bsp/peripherals/rs485.rsti

Replace the fixed tty device specification with the replacement |serial-uart|.

bsp: peripherals: rs485: use |serial-uart|

---

source/bsp/imx-common/peripherals/network.rsti

Add a more detailed description on how to configure network interfaces to use dynamic IP addresses in linux.

imx-common: network: more detail on how to configure dynamic IP in linux

---

source/bsp/imx9/imx93/display.rsti
source/bsp/imx9/imx93/imx93.rst
source/bsp/imx9/imx93/pd24.1.0.rst
source/bsp/imx9/imx93/pd24.1.1.rst
source/bsp/imx9/imx93/pd24.2.0.rst
source/bsp/imx9/imx93/pd24.2.1.rst
source/bsp/imx9/imx93/wireless-network.rsti
source/bsp/imx9/peripherals/canfd.rsti
source/bsp/imx9/peripherals/eeprom.rsti
source/bsp/imx9/peripherals/gpios.rsti
source/bsp/peripherals/wireless-network.rsti
source/conf.py

Update documentation for the i.MX93 PD24.2.1 release.
Changelog:
- update component version (Linux, U-Boot, Yocto, etc.)
- update line references in device-tree URL links
- rename SoM option extension overlays (unified with i.MX91)
- add phyboard-nash rev 1616.2
- improve WLAN/BT chapter for both boards (Segin uses PEB-WLBT-05, Nash uses PEB-WLBT-07)
- add mlan0 interface name note for PEB-WLBT-07 wireless adapter
- drop PEB-WLBT-05 specifics in general wireless-network.rsti chapter
- update CAN-FD chapter due to BSP changes
- update GPIO chapter due to BSP changes (libgpiod v2 was already part of previous release, so fix it now)
- update EEPROM chapter due to libgpiod v2 changes
- drop "BOOT/bootenv.txt" in favor of "/boot/bootenv.txt" in display.rsti chapter

i.MX93 BSP documentation update for PD24.2.1

---

source/bsp/imx9/imx95/alpha1.rst
source/bsp/imx9/imx95/display.rsti

For the alpha release of the imx95-libra we will include two overlays for two different displays. The current edt etml1010g3dra display and the new powertip ph128800t006-zhc01 display.

imx95: alpha1: add new powertip display

---

source/bsp/imx9/imx95/alpha1.rst

checked documentation and added links.
Links currently reference the branch since tags are not yet available.

imx95: alpha1: add RTC

---

source/bsp/imx-common/GoPoint/ML_Benchmark.rsti
source/bsp/imx-common/GoPoint/introduction.rsti
source/bsp/imx9/imx95/alpha1.rst

Add a section to imx(95) for instructions on how to run a NPU demo using the NXP GoPoint demo suite.

bsp: imx(95): add GoPoint ML Benchmark demo

---

source/conf.py

Github.com imposes rate limits after around 10 checks or so. It seems that this rate limit only counts for source file links, but not for general projects. For now we can ignore those files and instead manually checking those links from time-to-time with high wait times to not run into the rate-limit.
unix.stackexchange.com and jedec.org show other errors but the pages generally work. This is likely also recent measures to mitigate the impact of AI crawler.
Note:
This is a fix to make the linkcheck work reliably for other links. The situation seems to change rapidly with multiple websites recently and we may need to find other solutions for a linkcheck. First I would like to make the linkcheck work again (even if that means ignoring some domains). Then we can observe the behavior in the …

linkcheck: add some urls to ignore list

---

source/bsp/imx9/imx95/alpha1.rst
source/bsp/imx9/imx95/peripherals/tm.rsti

The i.MX95 has next to SoC internal temperature sensors also temperature sensors on the PMICs and also some additional i2c sensors on the SoM.

BSPIMX95-66: bsp: imx9: Add i.MX95 specific thermal management chapter

---

source/bsp/imx9/imx93/head.rst
source/bsp/imx9/imx93/imx93.rst
source/conf.py

Add HEAD BSP manual for i.MX93 based on the latest PD24.2.1 release. It can be used to write documentation during BSP development cycle instead of at the end of the development cycle like we have done so far. This aligns the i.MX93 platform with other i.MX products from PHYTEC.
This was proposed by @jonas-rem in the PR #283.

Add HEAD BSP manual for i.MX93

---

source/sphinx/static/css/phytec-theme.css

Change the navbar color showing up for smaller screens, like mobile devices, to match the teal used for the regular navbar.
Before: 
After:

sphinx: static: css: Change mobile navbar color

---

source/bsp/imx9/imx93/head.rst

Add information about document ID for i.MX93 BSP Manual. This aligns i.MX93 manual with other manuals for PHYTEC i.MX family of products.

bsp: imx9: imx93: head: Add doc-id information

---

source/bsp/imx8/imx8mp-libra-fpsc/head.rst

Update to Ethernet interface naming conventions
(ETH0/ETH1 instead of ethernet0/ethernet1 as printed on board) Removal of wireless network and Bluetooth related sections Addition of secondary Ethernet interface U-Boot configuration instructions

imx8mp-libra-fpsc: update network section

---

source/bsp/imx9/imx95/alpha1.rst
source/bsp/imx9/imx95/head.rst
source/bsp/imx9/imx95/peripherals/gpu.rsti

When running benchmark tests on MALI G310 GPU of i.MX95 FPSC WESTON_FORCE_RENDERER is enabled and sourced in /etc/environment on the target.
Ref: https://www.nxp.com/docs/en/user-guide/IMX_GRAPHICS_USERS_GUIDE.pdf

imx9: imx95: peripherals: add and update gpu section

---

source/bsp/imx9/imx95/quickstart-alpha1.rst

on prototype hardware libra revision .0 and .1, usb-pd will pass the 24V supplied via phoenix connector back via the USB cable. To avoid users destroying their hardware, remove explanation chapter of USB-PD.

bsp: imx95-libra: remove USB-PD mention

---

source/bsp/imx8/imx8mm/head.rst
source/bsp/imx8/imx8mm/pd23.1.0.rst
source/bsp/imx8/imx8mm/pd25.1.0.rst
source/bsp/imx8/imx8mn/head.rst
source/bsp/imx8/imx8mn/pd23.1.0.rst
source/bsp/imx8/imx8mp-libra-fpsc/head.rst
source/bsp/imx8/imx8mp/head.rst
source/bsp/imx8/imx8mp/mainline-head.rst
source/bsp/imx8/imx8mp/pd23.1.0.rst
source/bsp/imx8/imx8mp/pd24.1.0_nxp.rst
source/bsp/imx8/imx8mp/pd24.1.1.rst
source/bsp/imx8/imx8mp/pd24.1.2.rst
source/bsp/peripherals/leds.rsti
source/bsp/template.rst

we still use the default text:
Here the LEDs blue-mmc, green-heartbeat, and red-emmc are on the |sbc|
make the names here and in the example configure able. Checked the names from the linked device trees to set the values for other platforms.

BSPIMX8M-3630: bsp: imx8mp-libra-fpsc: fix led names

---

source/bsp/imx-common/development/host_network_setup.rsti
source/bsp/imx8/imx8mm/pd25.1.0.rst
source/bsp/imx8/imx8mp/pd24.1.0_nxp.rst
source/bsp/imx9/imx95/alpha1.rst

For our vendor BSPs we are using static IPs by default. Now netboot with standardboot and static IPs are also possible and used as default. DHCP server setup is only needed when using dynamic IPs. Add a comment for that.

BSPIMX8M-3617 imx8: imx95: add comment about static IPs for netboot

---

source/coprocessor/coprocessor.rst

The PHYTEC-Messtechnik-GmbH GitHub organisation has been deleted. Relevant branches in the repositories have been transitioned to the phytec GitHub organisation.

coprocessor: fix link to example branch

---

source/bsp/fpsc-device-tree.rsti
source/bsp/imx8/imx8mp-fpsc/head.rst

For FPSC SoMs, rules set forth in the existing PHYTEC device tree concept are extended.
Document how FPSC is different to "normal" PHYTEC device tree concept.

BSPIMX8M-3674 add FPSC device tree concept documentation

---

source/conf.py

we often see 403 in our runners.

conf: don't check link of sourceforge.net

---

tox.ini

If you open a file with vim, a temporary *.swp is created. This trogger the build while editing. Because it is not directly used, this build is pointless.
Wait till we save the file to trigger the build by ignoring *.swp files.

tox: sphinx-build: stop updating while editing
